### ISSUE TITLE
Install other dependencies

### ISSUE THREAD

**Issue by paviro** [qistoph/MMM-autoinstall#1]
It should be possible to install other dependencies as well for more complex modules. Volumio does this via an `install.sh` script, not sure if this is the right approach but could be worth looking into: https://github.com/volumio/volumio-plugins/blob/master/plugins/music_service/spotify/install.sh

**Comment by qistoph** [comment]
This is already supported through the `npm install` command. Npm can run script during the installation on different times. For detailed information have a look here at the [NPM script documentation](https://docs.npmjs.com/misc/scripts).

**Comment by paviro** [comment]
Right! Completely forgot about that!
